### ISSUE TITLE
Speaking: [object Object] No response

### ISSUE THREAD

**Issue by sajeetharan** [peterjurkovic/pjTextToSpeech#1]
I am using your library as a dependency in my application, this works for the first time, after that it does not. I can see the request being passed and the response also comes as .mp3, but i cannot hear the audio.

Speaking: [object Object]

How to solve this?

Here is my code:

 $scope.commentary = function(widget) {
            TTSConfig.url = 'http://tts.peterjurkovic.com/tts-backend/index.php';
            var tts = new TTSAudio();
            var comment = "";
            var chunks = [];
            if (widget.uniqueType === "ElasticSearch") {
                $scope.dataSeries = widget.chartConfig.series;
                $scope.dataCategories = widget.chartConfig.xAxis.categories;
                tts.speak({
                    text: 'Jay you are adding  widget',
                    lang: 'en'// you can add additional params which will send to server
                });      
                $scope.$on(TTS_EVENTS.SUCCESS, function() {
                                    $log.info('Successfully done!')
                });
                $scope.$on(TTS_EVENTS.ERROR, function() {
                    $log.info('An unexpected error has occurred');
                });
                $scope.$on(TTS_EVENTS.PENDING, function(text) {
                    $log.info('Speaking: ' + text);
                });
               
            }

**Comment by peterjurkovic** [comment]
If you've been using `http://tts.peterjurkovic.com/tts-backend/index.php` url for TTS, the reason is that Google have started use the captcha protection for the server where is the script running. From this server have been sent a lot of TTS requests which Gooogle detects. 

Returned file is not really mp3 file, but its image which is not browser able to decode. The solution should be move the script to difrenet server.

**Comment by sajeetharan** [comment]
You mean deploy the script on a different server? why is it working when we type "Hello" but not for other words!

**Comment by peterjurkovic** [comment]
Yes, resp. different IP address.
It's working because all audio files are being cached. Before every request the application check if the given text was already translated in case yes will not requested Google servers but will be used the cached resource. (Second pronunciation is much more faster)

**Comment by sajeetharan** [comment]
i Have hosted on a different server, still i am getting the same issue

**Comment by peterjurkovic** [comment]
In this case Google introduced the captcha protection for all user (or IP address ranges)

**Comment by sajeetharan** [comment]
what's the solution? is there any alternative?

**Comment by peterjurkovic** [comment]
I'll take a look on possible solution and implement it (if any).
